# Site settings
title: Draybee
email: 
description: > # this means to ignore newlines until "baseurl:"
  Social platform only for those people who is not ashamed of what they have in their garage
baseurl: "/draybee" # the subpath of your site, e.g. /blog/
url: "https://draybee.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]